// assets/vue/components/posts/header/PostHeader.vue
<script setup>
  import moment from 'moment';

  defineProps({
    avatar: {},
    author_name: {},
    date: {},
    profile_url: {},
  });
</script>

<template>
  <div class="post-header">
    <div class="post-author d-flex">
      <a v-bind:href=profile_url><img v-bind:src=avatar alt=""></a>
      <div class="author-name post-date">
        <div class="name"><a v-bind:href=profile_url>{{ author_name }}</a></div>
        <div class="date">
          <i content="fas fa-globe-europe"></i>
          {{ moment(date).fromNow() }}
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
  .author-name {
    margin-left: 15px;
  }

  img {
    width: 45px;
    height: 45px;
    background-position: center;
    background-size: cover;
    background-repeat: no-repeat;
    border-radius: 50%;
    background-color: #efefef;
  }

  .post-date .date {
    font-size: 13px
  }
</style>

// assets/js/components/posts/header/PostHeader.jsx
import moment from 'moment';

function PostHeader ({ author, date }) {
  let url = author.profile_url ?? author.profile_url;
  let avatar = author.avatar_image ?? author.avatar_image;
  console.log(url);

  return (
    <div className="post-header">
      <div className="post-author d-flex">
        <a href={url}><img src={avatar} alt=""/></a>
        <div className="author-name post-date">
          <div className="name"><a href={url}>{author.fullname}</a></div>
          <div className="date">{moment(date).fromNow()}</div>
        </div>
      </div>
    </div>
  );
}

export default PostHeader;
