// assets/js/components/posts/content/PostContent.jsx
import Content from './parts/Content';
import FeaturedImage from './parts/FeaturedImage';

export default function PostContent ({ content, featured_image, title }) {
  return (
    <div className="post-content">
      <Content content={content}/>
      <FeaturedImage featured_image={featured_image} title={title}/>
    </div>
  );
}

// assets/vue/components/posts/content/PostContent.vue
<script setup>
  import Content from './partials/Content';
  import FeaturedImage from './partials/FeaturedImage';

  defineProps({
    content: {},
    featured_image: {},
    title: {},
  });
</script>

<template>
  <div class="post-content">
    <Content :content=content />
    <FeaturedImage :featured_image=featured_image :title=title />
  </div>
</template>
