// assets/vue/components/posts/content/PostContent.vue
<script setup>
  import Content from './partials/Content';
  import FeaturedImage from './partials/FeaturedImage';

  defineProps({
    content: {},
    featured_image: {},
    title: {},
  });
</script>

<template>
  <div class="post-content">
    <Content :content=content />
    <FeaturedImage :featured_image=featured_image :title=title />
  </div>
</template>

// assets/js/components/posts/PostContent.jsx
import FeaturedImage from './parts/FeaturedImage';
import Content from './parts/Content';

export default function PostContent ({ content, postFeaturedImage, postTitle }) {
  return (
    <div className="post-content">
      <Content content={content}/>
      <FeaturedImage postFeaturedImage={postFeaturedImage} postTitle={postTitle}/>
    </div>
  );
}
